[package]
name = "beammm-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
beammm = "0.1.0"
egui = "0.28"
eframe = { version = "0.28", features = ["default"] }

env_logger = { version = "0.11" }

egui_extras = { version = "0.28" }
